// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wrapper.proto

package wrapperGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CriarUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`      // E-mail do novo usuário
	Senha         string                 `protobuf:"bytes,2,opt,name=senha,proto3" json:"senha,omitempty"`      // Senha temporária
	Nome          string                 `protobuf:"bytes,3,opt,name=nome,proto3" json:"nome,omitempty"`        // Nome novo do usuário
	Sistema       bool                   `protobuf:"varint,4,opt,name=sistema,proto3" json:"sistema,omitempty"` // TENANT: Define qual o tenant que o novo usuário será inserido (web / fabrica)
	Grupo         string                 `protobuf:"bytes,5,opt,name=grupo,proto3" json:"grupo,omitempty"`      // Caso seja na web, o usuário deve fazer parte do grupo de sua empresa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarUsuarioRequest) Reset() {
	*x = CriarUsuarioRequest{}
	mi := &file_wrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarUsuarioRequest) ProtoMessage() {}

func (x *CriarUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarUsuarioRequest.ProtoReflect.Descriptor instead.
func (*CriarUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_wrapper_proto_rawDescGZIP(), []int{0}
}

func (x *CriarUsuarioRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CriarUsuarioRequest) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

func (x *CriarUsuarioRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CriarUsuarioRequest) GetSistema() bool {
	if x != nil {
		return x.Sistema
	}
	return false
}

func (x *CriarUsuarioRequest) GetGrupo() string {
	if x != nil {
		return x.Grupo
	}
	return ""
}

var File_wrapper_proto protoreflect.FileDescriptor

const file_wrapper_proto_rawDesc = "" +
	"\n" +
	"\rwrapper.proto\x12\vwrapperGrpc\x1a\x1bgoogle/protobuf/empty.proto\"\x85\x01\n" +
	"\x13CriarUsuarioRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05senha\x18\x02 \x01(\tR\x05senha\x12\x12\n" +
	"\x04nome\x18\x03 \x01(\tR\x04nome\x12\x18\n" +
	"\asistema\x18\x04 \x01(\bR\asistema\x12\x14\n" +
	"\x05grupo\x18\x05 \x01(\tR\x05grupo2]\n" +
	"\x11FusionAuthWrapper\x12H\n" +
	"\fCriarUsuario\x12 .wrapperGrpc.CriarUsuarioRequest\x1a\x16.google.protobuf.EmptyB4Z2fusionauth-module/grpc/gerados/wrapper;wrapperGrpcb\x06proto3"

var (
	file_wrapper_proto_rawDescOnce sync.Once
	file_wrapper_proto_rawDescData []byte
)

func file_wrapper_proto_rawDescGZIP() []byte {
	file_wrapper_proto_rawDescOnce.Do(func() {
		file_wrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wrapper_proto_rawDesc), len(file_wrapper_proto_rawDesc)))
	})
	return file_wrapper_proto_rawDescData
}

var file_wrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wrapper_proto_goTypes = []any{
	(*CriarUsuarioRequest)(nil), // 0: wrapperGrpc.CriarUsuarioRequest
	(*emptypb.Empty)(nil),       // 1: google.protobuf.Empty
}
var file_wrapper_proto_depIdxs = []int32{
	0, // 0: wrapperGrpc.FusionAuthWrapper.CriarUsuario:input_type -> wrapperGrpc.CriarUsuarioRequest
	1, // 1: wrapperGrpc.FusionAuthWrapper.CriarUsuario:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wrapper_proto_init() }
func file_wrapper_proto_init() {
	if File_wrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wrapper_proto_rawDesc), len(file_wrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wrapper_proto_goTypes,
		DependencyIndexes: file_wrapper_proto_depIdxs,
		MessageInfos:      file_wrapper_proto_msgTypes,
	}.Build()
	File_wrapper_proto = out.File
	file_wrapper_proto_goTypes = nil
	file_wrapper_proto_depIdxs = nil
}
